import type { NextPage } from 'next'
import Head from 'next/head'
import Chat from '../components/Chat'
import ChatView from '../components/ChatView'
import SideBar from '../components/SideBar'

const Home: NextPage = () => {
  return (
    <div className={`h-screen `}>
      <Head>
        <title >Dicord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/discord.svg" />
      </Head>

      <main className={` flex  `}>
        <Chat />
        <SideBar />
        <ChatView/>
      </main>
    </div>
  )
}

export default Home
